version: "3.9"

services:
  imdb-api:
    image: csluispaulo/imdb-api
    command: ["/wait-for-it.sh", "imdb-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: imdb-mysql
    ports:
      - "8080:8080"
    networks:
      - imdb-network
    depends_on:
      - imdb-mysql
   
  imdb-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "java"      
    ports:
      - "3306:3306"
    networks:
      - imdb-network        

networks:
  imdb-network:
    driver: bridge      